# -*- coding: utf-8 -*-
"""Copy of product_agent _ayeta_jireh.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1osFFrpuEl3DVxh5PILsnHK7LxbXurs-9
"""

!pip install llama-index openai # we use this inorder to be able to access tools such as openai

import os
os.environ["OPENAI_API_KEY"] = "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"  # actual key for access

products = [
    {"id": 1, "name": "Wireless Mouse", "price": 25, "description": "Ergonomic wireless mouse", "approved": True},
    {"id": 2, "name": "Mechanical Keyboard", "price": 75, "description": "RGB mechanical keyboard", "approved": True},
    {"id": 3, "name": "Smart Watch", "price": 120, "description": "Fitness tracking watch", "approved": False}
]

from llama_index.core.tools import FunctionTool# this enables us to add tool functionality to our agent
#the function allows for the agent to check from the global products list which products are approved and serach prices
def search_products(query: str) -> str:
    approved = [p for p in products if p["approved"]]
    if "under" in query:
        amount = int("".join(filter(str.isdigit, query)))
        approved = [p for p in approved if p["price"] < amount]
    if not approved:
        return "No approved products found."
    return "\n".join([f"{p['name']} (${p['price']}): {p['description']}" for p in approved])
#use functiontool inorder to avoid json format
product_tool = FunctionTool.from_defaults(
    fn=search_products,
    name="product_search",
    description="Search approved products by name or price"
)

from llama_index.core.agent import ReActAgent# this enables the agent to plan step by step
from llama_index.llms.openai import OpenAI # enables access to openai api
from llama_index.core.memory import ChatMemoryBuffer# allows us to add memory to the agent

# Memory for multi-turn chat
memory = ChatMemoryBuffer.from_defaults(token_limit=2000)#this enables us to split the tokens processed into smaller chunks

# OpenAI LLM
llm = OpenAI(model="gpt-4o-mini", temperature=0.3)

# Create the agent
agent = ReActAgent(
    tools=[product_tool],
    llm=llm,
    memory=memory,
    verbose=True
)